name = "sparklefish-client"
account_id = "151bc8670b862fa7d694cf7246a2c0dc"
compatibility_date = "2025-05-07"
preview_urls = false
main = "./worker/index.ts"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[observability]
enabled = true

[env.test]

[env.test.route]
pattern = "test.fanjam.live"
custom_domain = true

[env.test.vars]
API_DOMAIN = "api-test.fanjam.live"
INJECT_METADATA = "true"

[env.prod]

[env.prod.route]
pattern = "fanjam.live"
custom_domain = true

[env.prod.vars]
API_DOMAIN = "api.fanjam.live"
INJECT_METADATA = "true"
