# fly.toml app configuration file generated for sparklefish-noco-test on 2025-05-02T06:43:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sparklefish-noco-test"
primary_region = "bos"

[build]
image = "nocodb/nocodb:latest"

[env]
NC_PUBLIC_URL = "https://sparklefish-noco-test.fly.dev"
NC_INVITE_ONLY_SIGNUP = "true"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
