# fly.toml app configuration file generated for sparklefish-noco-playground on 2025-05-08T23:24:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sparklefish-noco-playground'
primary_region = 'bos'

[build]
  image = 'ghcr.io/justlark/nocodb:latest'

[env]
  NC_PUBLIC_URL = 'https://playground.fanjam.live'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
