app: sparklefish-noco-playground-592072
primary_region: iad
build:
  image: ghcr.io/justlark/nocodb-fanjam:0.265.1
http_service:
  internal_port: 8080
  force_https: true
  auto_stop_machines: "suspend"
  auto_start_machines: true
  min_machines_running: 0
  processes:
    - app
vm:
  - memory: 1gb
    cpu_kind: shared
    cpus: 2
