app = "sparklefish-noco-playground"
primary_region = "bos"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1

[build]
image = "ghcr.io/justlark/nocodb:latest"

[env]
NC_PUBLIC_URL = "https://playground.fanjam.live"
NC_S3_BUCKET_NAME = "sparklefish-noco-playground"
NC_S3_ENDPOINT = "https://151bc8670b862fa7d694cf7246a2c0dc.r2.cloudflarestorage.com/sparklefish-noco-playground"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
