app: sparklefish-noco-playground-592072
primary_region: iad
build:
  image: nocodb/nocodb:latest
env:
  NC_PUBLIC_URL: https://playground.fanjam.live
  NC_S3_BUCKET_NAME: sparklefish-noco-playground
  NC_S3_REGION: auto
  NC_S3_ENDPOINT: https://151bc8670b862fa7d694cf7246a2c0dc.r2.cloudflarestorage.com/sparklefish-noco-playground
  NC_INVITE_ONLY_SIGNUP: "true"
  NC_ADMIN_EMAIL: system@fanjam.live
  NC_CACHE_PREFIX: "sparklefish:env:playground:noco"
http_service:
  internal_port: 8080
  force_https: true
  auto_stop_machines: true
  auto_start_machines: true
  min_machines_running: 0
  processes:
    - app
vm:
  - memory: 1gb
    cpu_kind: shared
    cpus: 2
