title: FanJam Architecture Diagram {
  shape: text
  near: top-center
  style: {
    font-size: 40
  }
}

client: Attendee {shape: person}
organizer: Organizer {shape: person}
admin: Admin {shape: person}

cf: Cloudflare {
  client: Client Worker {shape: queue}
  server: Server Worker {shape: queue}
  noco: NocoDB Worker {shape: queue}
  client-cdn: Client CDN {shape: cloud}
  noco-cdn: NocoDB CDN {shape: cloud}
  kv: Clouflare KV {shape: cylinder}
  r2: Cloudflare R2 {shape: cylinder}
}

fly: Fly.io {
  noco: NocoDB {shape: queue}
}

neon: Neon {
  pg: Postgres Cluster {
    noco: NocoDB DB {shape: cylinder}
    worker: Worker DB {shape: cylinder}
  }
}

mailersend: MailerSend {
  smtp: SMTP {shape: cloud}
}

cf.client <- client
cf.client-cdn <- cf.client

cf.server <- client
cf.server <- admin
cf.kv <- cf.server

fly.noco -> cf.r2
fly.noco <- cf.server
cf.noco <- organizer
cf.noco-cdn <- cf.noco
fly.noco <- cf.noco

neon.pg.noco <- fly.noco
neon.pg.worker <- cf.server

mailersend.smtp <- fly.noco
