client: Browser {shape: person}
organizer: Browser {shape: person}
admin: Admin Tools {shape: person}

cf: Cloudflare {
  client: Client Worker {shape: queue}
  server: Server Worker {shape: queue}
  cdn: CDN {shape: cloud}
  kv: Clouflare KV {shape: cylinder}
  r2: Cloudflare R2 {shape: cylinder}
}

fly: Fly.io {
  noco: NocoDB {shape: queue}
}

neon: Neon {
  pg: Postgres Cluster {
    noco: NocoDB DB {shape: cylinder}
    worker: Worker DB {shape: cylinder}
  }
}

upstash: Upstash {
  redis: Redis DB {shape: cylinder}
}

mailersend: MailerSend {
  smtp: SMTP {shape: cloud}
}

cf.client <- client
cf.cdn <- cf.client

cf.server <- client
cf.server <- admin
cf.kv <- cf.server

fly.noco -> cf.r2
fly.noco <- cf.server
fly.noco <- organizer

neon.pg.noco <- fly.noco
neon.pg.worker <- cf.server

upstash.redis <- fly.noco

mailersend.smtp <- fly.noco
