title: FanJam Caching Flow Diagram {
  shape: text
  near: top-center
  style: {
    font-size: 40
  }
}

browser: Browser {shape: person}
local: Local Storage {shape: cylinder}
edge: Edge Cache {shape: cloud}
kv: Persistent Cache {shape: cloud}
noco: NocoDB {shape: cylinder}
error: Error {shape: hexagon}
backoff: Back Off {shape: hexagon}

question-fresh: Edge cache\nfresh? {shape: diamond}
question-healthy-populated: NocoDB\nhealthy? {shape: diamond}
question-healthy-empty: NocoDB\nhealthy? {shape: diamond}
question-populated: Persistent cache\npopulated? {shape: diamond}

local <- browser: Fetch
question-fresh <- browser: Fetch

question-populated <- question-fresh: No
kv <- question-populated: Yes
question-healthy-populated <- question-populated: Yes
question-healthy-empty <- question-populated: No
backoff <- question-healthy-populated: No
error <- question-healthy-empty: No
edge <- question-fresh: Yes
noco <- question-healthy-populated: Yes
noco <- question-healthy-empty: Yes

kv <- noco: Refresh
edge <- noco: Refresh
local <- edge: Refresh
local <- kv: Refresh
local <- noco: Refresh
browser <- kv: Trigger refetch
edge <- edge: Expire
