ARG NOCODB_IMAGE=nocodb/nocodb:latest

FROM $NOCODB_IMAGE AS nocodb

FROM caddy:2-alpine

RUN apk add --no-cache nodejs npm

COPY --from=nocodb /usr/src /usr/src
WORKDIR /usr/src/app

RUN mkdir -p /etc/caddy
COPY Caddyfile /etc/caddy/Caddyfile

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

EXPOSE 8080
CMD ["/usr/local/bin/start.sh"]
