name = "nocodb"
account_id = "151bc8670b862fa7d694cf7246a2c0dc"
compatibility_date = "2025-05-07"
preview_urls = false
main = "./index.ts"

[assets]
directory = "./public/"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[observability]
enabled = true
