name: "Playwright"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: "Install Client Dependencies"
        working-directory: ./client/
        run: npm ci

      - name: "Install Playwright Dependencies"
        working-directory: ./playwright/
        run: npm ci

      - name: "Install Playwright Browsers"
        working-directory: ./playwright/
        run: npx playwright install --with-deps

      - name: "Run Playwright Tests"
        working-directory: ./playwright/
        run: npx playwright test

      - name: "Upload Artifacts"
        working-directory: ./playwright/
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
